apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
  labels:
    name: hello
spec:
  replicas: 1
  selector:
    name: hello
  template:
    metadata:
     labels:
       name: hello
    spec:
     containers:
     - name: hello
       image: 192.168.146.133/hello/hello:<BUILD_TAG>
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 8080
