apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-v0.1
  labels:
    app: hello
    var: v0.1
spec:
  replicas: 2
  selector:
    app: hello
    var: v0.1
  template:
    metadata:
     labels:
       app: hello
       var: v0.1
    spec:
     containers:
     - name: hello
       image: 192.168.146.133/hello/hello:<BUILD_TAG>
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 8080
